### ISSUE TITLE
Install plugin using vundle

### ISSUE THREAD

**Issue by AlekseiSmirnov** [brennier/vimtexer#1]
I think readme file lacks instructions on the installation process. I tried to install plugin using vundle, it was downloaded but doesn't work for some reason

**Comment by Alex23rodriguez** [comment]
I had this same problem. I wish he would respond...

**Comment by brennier** [comment]
I suspect the problem is that you need to either create a dictionary with the name "g:vimtexer_<filetype>" in your vimrc or turn on the default dictionaries by adding "let g:vimtexer_usedefault = 1" in your vimrc. I turned off the default dictionaries at the moment because I've been meaning to trim them down. At the moment, they're more my "personal" dictionaries than true default dictionaries.

**Comment by brennier** [comment]
*create a dictionary with the name "g:vimtexer_[filetype]"

**Comment by Alex23rodriguez** [comment]
forgive my lack of knowledge.. I'm new to installing plugins.
I tried adding "let g:vimtexer_usedefault = 1" to my .vimrc (Does it matter if it is added before or after "Plugin 'brennier/vimtexer' " ?). I reinstalled the plugins and created a new vim file. I tried writing "prf" to check if it worked but got a couple errors instead (so at least it tried running it). How can I create a dictionary?

**Comment by brennier** [comment]
A simple example would be like this:
```
let g:vimtexer_math = {
    \'this' : 'isturnedintothis',
    \'alpha' : '\alpha ',
\}
```

I will update the README later today on how to make more advanced dictionary substitutions (like' prf'). For now, could you tell me the error you got with the default dictionaries?

**Comment by AlekseiSmirnov** [comment]
Tried again and now I succeded to install vimtexer using vundle
