### ISSUE TITLE
Regex Matching

### ISSUE THREAD

**Issue by Jab2870** [brennier/vimtexer#19]
Hi,
Thanks for building this plugin. It's great! I was going through my vimrc the other day and tidying it up. I noticed that a large part of it looks like this:

```vim
	\';ma'		: "$a$ ",
	\';mb'		: "$b$ ",
	\';mc'		: "$c$ ",
	........
	\';mx'		: "$x$ ",
	\';my'		: "$y$ ",
	\';mz'		: "$z$ ",
```

This works fine but it would (imho) look a lot tidier if we could do regex matching. These 26 lines would then become something like this:

```vim
	\';/m([a-z])/'		: "\$$1\$ ",
```

Obviously, the syntax used would be up to you. I have used a `$` on the RHS to access the value of the regex groups which obviously means the other `$` symbols need escaping.

I know one of your main goals with quicktex is to keep it fast and I know that regex matching can be slow but I really do belive that this would make maintaining the shortcut dictionaries much easier.

**Comment by brennier** [comment]
I actually have plans to rewrite this entire plugin; though, it'll have to wait until the summer. Regexes are definitely something I'd like to add. In particular, I think it would be cool to have keywords like `matrix\(\d\)\(\d\)`, which would expand into a `\1` by `\2` matrix. Additionally, I would like to add the ability to expand keywords after any "non-word character" (as defined by Vim) instead of just after pressing space. And finally, I want to open up the customization to allow people to define their own contexts and dictionaries for those contexts.

However, I think so many changes would be unfair to the people already using this plugin as it will break their configurations in quite a few different ways. As such, my current plan is simply to make a separate plugin. This will also give me the chance to change the marketing of the plugin away from "a plugin made for typing LaTeX more quickly" and more towards "a plugin that replaces and improves Vim abbreviations."
