### ISSUE TITLE
Add function-keys?

### ISSUE THREAD

**Issue by ghost** [brennier/vimtexer#22]
Hi! I use this great plugin in combination with vim-latex. I thought it would be intelligent to add to the dictionary something like:

`\'eqr'   : "Equation~\\eqref{eqn:\<F9>"`

which in theory opens the buffer with the choices of the possible citations. But the <F9> key input is not really working (I just get printed out: `Equation~\eqref{eqn:<F9>`). 

Can this be solved somehow? Is there a simple workaround? (I am no great programmer, so sorry for my ignorance..)

**Comment by brennier** [comment]
That is very strange. It seems like Vim's expression registers don't handle function keys properly. Even if you try to call feedkeys() in the expansion it will not work.

In any case, though, dictionary expansions in quicktex are based on the original meaning of the keys and ignores any rebindings you or a plugin may have done. After a quick grep through the vim-latex repository, it seems that vim-latex binds F9 to `<Plug>Tex_Completion`. Unfortunately, the `<Plug>` syntax means this function can only be used in a rebinding and cannot be called directly, so I see no simple solution in this case. You could modify vim-latex to expose this function so that you can call it, but that is probably more trouble than it's worth.

EDIT: Nevermind, it seems that `<Plug>Tex_Complete` is bound to `<Esc>:call Tex_Complete("default","text")<CR>` which is callable. Try something like this and let me know if it works for you:

`\'eqr' : "Equation~\\eqref{eqn:\<ESC>:call Tex_Complete(\"default\",\"text\")\<CR>",`

**Comment by ghost** [comment]
It appears to work splendidly! Thanks a lot! :-)

**Comment by brennier** [comment]
Not a problem, I'm glad it worked out
