### ISSUE TITLE
Reload dictionary

### ISSUE THREAD

**Issue by monsieurcoconut** [brennier/vimtexer#23]
Hi,
Thanks for the very useful plugin. I use it daily for my work!
There's one feature which would really enhance my experience though: the possibility of reloading the dictionary from within vim.
By that I mean that currently, when I edit `~/.vim/plugged/quicktex/ftplugin/tex.vim`, I have to exit vim and return to use the new shortcuts. Is there a way to reload the file directly from within vim?
Right now I just know that sourcing `~/.vimrc` doesn't work.
Thanks!
Adrien

**Comment by brennier** [comment]
Unfortunately, I think it'd be impossible to write something like this because the plugin doesn't know in which files the dictionaries are defined.

I wouldn't recommend editing the default dictionary in `~/.vim/plugged/quicktex/ftplugin/tex.vim` for a few reasons. The first is that if you update quicktex, either your changes will be overwritten or you'll get some kind of git merge error (depending on your plugin manager). The other reason is that the file has checks specifically so that it won't override any dictionaries that have already been defined.

Instead, you should put your dictionaries either in `~/.vimrc`, in `~/.vim/ftplugin/tex.vim`, or in some other file that you then source in `~/.vimrc`. Which ever option you choose, if you want to reload the dictionary, you'll just have to source the file that it's in.

**Comment by monsieurcoconut** [comment]
Hi, 
Thank you for the information, I was doing it the wrong way this whole time!
One more question, can I define a custom dictionary in a way that the new entries would simply be added to the ones loaded in the default dictionary? At the moment it seems that the entire dictionary is overwritten by sourcing my new tex.vim file.

**Comment by brennier** [comment]
I think the easiest solution would be to simply copy the dictionaries in `~/.vim/plugged/quicktex/ftplugin/tex.vim` to your tex.vim as a foundation and then add/remove your changes there.

**Comment by monsieurcoconut** [comment]
got it, thanks!
