### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by flossgeek** [brennier/vimtexer#27]
Is this project still supported for the current vim version? I can't get it to work, but maybe I'm missing something. After installing the plugin, do any additional steps need to be taken or should the plugin work right away? For me the latter isn't the case.

**Comment by brennier** [comment]
I tried installing the plugin from scratch, and you're correct that it didn't work on startup. The problem I found was that Vim has two latex filetypes now: `plaintex` and `tex`. I'm not sure when this happened; I don't recall `plaintex` existing when I made this plugin. The best solution I found was to add `let g:tex_flavor = 'latex'` in your `.vimrc` file. This will cause all `.tex` files to register as filetype `tex`.

Let me know if this solves your problem. In the meantime, I'll look into how to modify this plugin so that it supports both `plaintex` and `tex` filetypes.

**Comment by flossgeek** [comment]
Thank you, that worked excellent!
When I try to get the same functionality on markdown files however, it seems that Math Mode breaks (it lingers in the now quicktex_markdown dictionary). To do this, I copied the tex.vim file with all the dictionaries to another location (sourced it in ~/.vimrc) and edited the file by replacing every `g:quicktex_tex` with `g:quicktex_markdown`. What am I doing wrong?

**Comment by flossgeek** [comment]
Appending `a:ft == 'markdown'` in the expand.vim file seems to solve it.
Thanks for writing this great plugin by the way!

**Comment by brennier** [comment]
I'm surprised that I did not include `markdown` files when checking for math mode. I will add a new variable so that the user can specify which filetypes support math mode.

Unfortunately, I'm a bit busy right now as I'm moving to live in another country. It might be a few weeks before I can commit and push the new changes.

**Comment by brennier** [comment]
I've fixed the `tex` vs `plaintex` problem. The plugin will always set the filetype to `tex` for .tex files unless `g:quicktex_always_tex` is explicitly set to 0.

I've also added a variable called `g:quicktex_math_filetypes` so you can set other filetypes to use math mode. Files with filetype `markdown` are now set to use math mode by default.
